// Imports the helper directly (the distributed `.mjs`). Covers the pure
// vendor-sync core (ADR-0004 / A-534): the rendered banner+body a vendored copy
// must hold, and the drift detection that gates CI. The same assertions back the
// script's `--self-test`; this wires them into the vitest suite. Two layers are
// exercised: synthetic temp-repo fixtures (deterministic), and the REAL repo —
// the latter asserts the committed vendored copies are actually in sync, which is
// what `pnpm vendor:check` enforces in CI.
import {
  computeVendorPlan,
  detectDrift,
  renderVendored,
  writeVendored,
} from "../scripts/vendor-sync.mjs";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

describe("renderVendored", () => {
  it("prepends a generated do-not-edit banner naming the canonical source", () => {
    const out = renderVendored("lib/issue-keys.mjs", "export const x = 1;\n");
    expect(out).toMatch(
      /^\/\/ @generated by `pnpm vendor:sync` from lib\/issue-keys\.mjs/,
    );
    expect(out).toContain("DO NOT EDIT");
  });

  it("preserves the canonical body verbatim after the banner", () => {
    const body = "export const x = 1;\n";
    expect(renderVendored("lib/x.mjs", body).endsWith(body)).toBe(true);
  });
});

describe("detectDrift / writeVendored (synthetic repo)", () => {
  let root: string;

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), "vendor-sync-test-"));
    mkdirSync(join(root, "lib"), { recursive: true });
    writeFileSync(join(root, "lib", "issue-keys.mjs"), "export const a = 1;\n");
    writeFileSync(
      join(root, "lib", "base-branch.mjs"),
      "export const b = 2;\n",
    );
  });

  afterEach(() => {
    rmSync(root, { force: true, recursive: true });
  });

  it("flags every destination as missing before a sync", () => {
    const drift = detectDrift(root);
    expect(drift).toHaveLength(computeVendorPlan(root).length);
    expect(drift.every((entry) => entry.reason === "missing")).toBe(true);
  });

  it("is in sync immediately after writeVendored", () => {
    writeVendored(root);
    expect(detectDrift(root)).toEqual([]);
  });

  it("catches a hand-edited vendored copy as drift", () => {
    writeVendored(root);
    writeFileSync(
      join(root, "skills/changelog/scripts/lib/vendor/issue-keys.mjs"),
      "tampered\n",
    );
    const drift = detectDrift(root);
    expect(drift).toHaveLength(1);
    expect(drift[0].reason).toBe("drift");
    expect(drift[0].destination).toContain(
      "changelog/scripts/lib/vendor/issue-keys.mjs",
    );
  });
});

describe("the committed repo", () => {
  it("has no vendored drift (pnpm vendor:check would pass)", () => {
    expect(detectDrift()).toEqual([]);
  });
});
